### DISCUSSION TITLE
Fly.io template / Free cloud Pocket-ID instance

### DISCUSSION THREAD

**Discussion by poaudet** [pocket-id/pocket-id#181] [General]
Hi everyone!

Just sharing you my fly.toml config to run a pocket-id instance on [fly.io](https://fly.io/) free tier
To get it to work, I had to force PGID/PUID to root
Also, I had to force the entrypoint and cmd to be called at the right folder.
I think I could make it differently, but this is working for now!

Note that fly.io offer managed postgres instance. Didn't tried, but that could simplify the setup!

Have fun! And if you have any improvement to suggest, feel free to share it!

```toml
app = 'pocket-id'
primary_region = 'yyz'

[build]
  image = 'stonith404/pocket-id'

[env]
  PGID = '0'
  PUBLIC_APP_URL = 'https://custom.domain.com'
  PUID = '0'
  TRUST_PROXY = 'false'

[[mounts]]
  source = 'data'
  destination = '/app/backend/data'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  size = 'shared-cpu-1x'

[experimental]
entrypoint = ["sh", "/app/scripts/docker/create-user.sh"]
cmd = ["sh", "/app/scripts/docker/entrypoint.sh"]

```
