### DISCUSSION TITLE
Struggling with traefik

### DISCUSSION THREAD

**Discussion by elchanly** [pocket-id/pocket-id#213] [Q&A]
Finally done. Leave here for those who, like me, where googling and googling for the answer... (only relevant parts of the config)
static:

````

experimental:
  plugins:
[...]
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.6.1" 
authSources:                     (i suspect this section is not needed...)
  oidcSource:
    oidc:
      issuer: http://pocketid:80
      ClientId: client_id_from_pocketid
      ClientSecret: client_secret_from_pocketid`
````

dynamic: 

````
http:  
  routers:    [...]
    oidc-callback-router:
      entryPoints:
        - https
      rule: "PathPrefix(`/oidc/callback`)"
      service: pocketid_service
  services: 
    pocketid_service:
      loadBalancer:
        servers:
          - url: "http://pocketid:80"
  middlewares:
  [...]
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          source: oidcSource
          Provider:
            Url: http://pocketid:80
            ClientId: client_id_from_pocketid
            ClientSecret: client_secret_from_pocketid
            UsePkce: false # Or use PKCE if your Provider supports this
          Scopes: ["openid", "profile", "email"]
          CallbackUri: "https://mydomain/oidc/callback" <<<<<<<<<<<<<the problem was here, only use /oidc/callback (also in pocketid config)
          SessionCookie:
            Domain: ".mydomain"  
 

````
