### DISCUSSION TITLE
Does it support auth through headers?

### DISCUSSION THREAD

**Discussion by kingp0dd** [pocket-id/pocket-id#228] [Q&A] [answered]
I'm trying to get it to work with frigate

https://docs.frigate.video/configuration/authentication/

It seems to only accept header auth and not token auth? Can pocket id also pass any of this

Remote-User
Remote-Groups
Remote-Email
Remote-Name
X-Forwarded-User
X-Forwarded-Groups
X-Forwarded-Email

To oauth2-proxy and to frigate so frigate would know which user logged in?

**Comment by kmendell** [comment]
Hi @kingp0dd Pocket ID does support using oauth2-proxy see the guide here: https://pocket-id.org/docs/guides/proxy-services

**Reply by kingp0dd** [reply]
I was able to get Frigate + pocket-id + oauth2-proxy to work. The only thing missing is Frigate is unable to identify which user logged in. Per their docs, they use headers to identify the user. In oauth2-proxy, I enabled passing of headers, but it seems pocket-id is not passing auth headers such as user/email, but just auth token? I wasn't able to find anything about headers in the link you provided. I'm also not sure if I was able to explain and use the terms correctly.

Here's my working config right now for this setup (Frigate + pocket-id + oauth2-proxy):


```
services:
  frigate:
    container_name: frigate
    # privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 780mb # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/healthcheck.sh:/healthcheck.sh
      - ${DOCKER_MNT_FOLDER}/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      # - "8971:8971" # Web UI
      # Internal unauthenticated access. Expose carefully:
      - 5000:5000 
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD
      FRIGATE_MQTT_USER: $FRIGATE_MQTT_USER
      FRIGATE_MQTT_PASSWORD: $FRIGATE_MQTT_PASSWORD
      # LIBVA_DRIVER_NAME: i965
    networks:
      - frigate
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
    deploy:
      resources:
        limits:
          memory: '3.5g'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.routers.frigate.rule=Host(`frigate.domain.com`)"
      - "traefik.http.services.frigate.loadbalancer.server.port=8971"
      - "traefik.http.routers.frigate.tls=true"
      - "traefik.http.routers.frigate.tls.certresolver=cloudflare-domaincom"
      - "traefik.http.routers.frigate.middlewares=frigate-proxy-secret-auth"
      - "traefik.http.routers.frigate.tls.domains[0].main=domain.com"
      - "traefik.http.routers.frigate.tls.domains[0].sans=*.domain.com"
      - "traefik.http.routers.frigate.middlewares=oauth-errors,oauth-auth,frigate-proxy-secret-auth"
      - "traefik.http.middlewares.frigate-proxy-secret-auth.headers.customrequestheaders.X-Proxy-Secret=${FRIGATE_PROXY_AUTH_SECRET}"
      - "traefik.http.middlewares.oauth-errors.errors.status=401-403"
      - "traefik.http.middlewares.oauth-errors.errors.service=oauth2-frigate"
      - "traefik.http.middlewares.oauth-errors.errors.query=/oauth2/sign_in?rd={url}"
      - "traefik.http.middlewares.oauth-auth.forwardAuth.address=https://oauth-frigate.domain.com/oauth2/auth"
      - "traefik.http.middlewares.oauth-auth.forwardAuth.trustForwardHeader=true"


  oauth2-frigate:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-frigate
    hostname: oauth2-frigate
    # command: --config /oauth2-proxy.cfg
    ports: []
    # volumes:
    #   - "./oauth2-proxy/oauth2-proxy.cfg:/oauth2-proxy.cfg"
    networks:
      - frigate
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_COOKIE_SECRET}
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_EMAIL_DOMAINS: "gmail.com"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://id.domain.com"
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      # OAUTH2_PROXY_REDIRECT_URL: "https://oauth2-frigate.domain.com/oauth2/callback" # does not redirect after login
      OAUTH2_PROXY_REDIRECT_URL: "https://frigate.domain.com/oauth2/callback"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_COOKIE_DOMAINS: ".domain.com" # REQUIRED SO COOKIE CAN BE READ ON ALL SUBDOMAINS.
      OAUTH2_PROXY_WHITELIST_DOMAINS: ".domain.com" # REQUIRED TO ALLOW REDIRECTION BACK TO ORIGINAL REQUESTED TARGET.
      # MANDATORY OPTION WHEN USING OAUTH2-PROXY WITH TRAEFIK
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      # REQUIRED FOR TRAEFIK WITH FORWARDAUTH AND STATIC UPSTREAM CONFIGURATION 
      # OAUTH2_PROXY_UPSTREAMS: "static://202"
      OAUTH2_PROXY_UPSTREAMS: "http://frigate:8971"
      # THE FOLLOWING OPTION SKIP THE PAGE REQUESTING THE USER
      # TO CLICK ON A BUTTON TO BE REDIRECTED TO THE IDENTITY PROVIDER
      # IT CAN BE ACTIVATED ONLY WHEN TRAEFIK IS NOT CONFIGURE WITH
      # THE ERROR REDIRECTION MIDDLEWARE AS THIS EXAMPLE.
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2-frigate.entrypoints=websecure"
      - "traefik.http.routers.oauth2-frigate.rule=Host(`frigate.domain.com`) || Host(`oauth2-frigate.domain.com`) && PathPrefix(`/oauth2/`)"
      - "traefik.http.routers.oauth2-frigate.middlewares=auth-headers,frigate-proxy-secret-auth"
      - "traefik.http.middlewares.frigate-proxy-secret-auth.headers.customrequestheaders.X-Proxy-Secret=${FRIGATE_PROXY_AUTH_SECRET}"
      - "traefik.http.middlewares.auth-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.auth-headers.headers.stsSeconds=315360000"
      - "traefik.http.middlewares.auth-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.auth-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.auth-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.auth-headers.headers.sslHost=domain.com"
      - "traefik.http.middlewares.auth-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.auth-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.auth-headers.headers.frameDeny=true"
      - "traefik.http.routers.oauth2-frigate.tls=true"
      - "traefik.http.routers.oauth2-frigate.tls.certresolver=cloudflare-domaincom"
      - "traefik.http.routers.oauth2-frigate.tls.domains[0].main=domain.com"
      - "traefik.http.routers.oauth2-frigate.tls.domains[0].sans=*.domain.com"
      - "traefik.http.services.oauth2-frigate.loadbalancer.server.port=4180"

networks:
  frigate: null

```

**Reply by kmendell** [reply]
@kingp0dd Oh gotcha i missunderstood, Ill admit im not sure if Pocket ID would pass those headers . @stonith404 Can you chime in? From review the code i dont see anything related to this, but im not 100% sure.

**Reply by stonith404** [reply]
I don't use oauth2-proxy because of that I can't really help you, sorry. The issue is probably with your oauth2-proxy configuration as it is responsible to generate the headers, not Pocket ID.

**Reply by kingp0dd** [reply]
Thanks i will look into it more. From the docs, they say i only need to include this which i have

OAUTH2_PROXY_PASS_USER_HEADERS: "true"

May i ask from where oauth2-proxy will get the headers? If i login from pocket-id using 2 different users or passkeys, how will oauth2-proxy know? Doesn't it need to get it from pocket-id at some point

**Reply by stonith404** [reply]
As soon as you visit Frigate the first time, oauth2-proxy redirects you to Pocket ID. You then sign in with your passkey and get redirected back to oauth2-proxy with your user information (not directly with your user information but it's not really relevant how it actually works). After that, the job of Pocket ID is done because oauth2-proxy has gotten the user information. oauth2-proxy will then have to create the mentioned headers (based on the user information received) and pass them to Frigate. 

So basically Pocket ID is only responsible for checking your passkey and giving your information to oauth2-proxy. Theoretically you could shutdown Pocket ID after you get redirected back.

**Reply by kingp0dd** [reply]
It's a bit clearer now. 

> As soon as you visit Frigate the first time, oauth2-proxy redirects you to Pocket ID. You then sign in with your passkey and get redirected back to oauth2-proxy with your user information

What information does pocket id pass back to oauth2-proxy after signing in with passkey? Does it include username/user so that oauth2-proxy has information that it can convert to a header that frigate needs:

X-Forwarded-User
X-Forwarded-Preferred-Username

**Reply by stonith404** [reply, marked as answer]
It should return `"sub", "given_name", "family_name", "name", "email", "email_verified", "preferred_username"`.

**Reply by kingp0dd** [reply]
It's the ones defined here right:

"given_name":         user.FirstName,
"family_name":        user.LastName,
"name":               user.FullName(),
"preferred_username": user.Username,

I was getting "name" in oauth2proxy, maybe that's why. I should be getting
preferred_username instead. I will try this again.
Thank you

**Reply by kingp0dd** [reply]
Confirming that it works now. It should be preferred_username since that's
the username from pocket-id

  header_map:
    user: X-Forwarded-Preferred-Username


from Frigate docs, these are the only supported header mappings:

Remote-User
Remote-Groups
Remote-Email
Remote-Name
X-Forwarded-User
X-Forwarded-Groups
X-Forwarded-Email
X-Forwarded-Preferred-Username
X-authentik-username
X-authentik-groups
X-authentik-email
X-authentik-name
X-authentik-uid
My config now works and frigate is able to identify the correct user. For
anyone else trying to make it work, I posted the frigate + traefik +
pocket-id configs above.

Thanks for pointing me to the right direction

**Reply by jsapede** [reply]
Wild you mind posting your complète setup including traefik configs ? I'm stuck

**Comment by kingp0dd** [comment]
It's the ones defined here right:

"given_name":         user.FirstName,
"family_name":        user.LastName,
"name":               user.FullName(),
"preferred_username": user.Username,

I was getting "name" in oauth2proxy, maybe that's why. I should be getting
preferred_username instead. I will try this again.
Thank you

**Comment by kingp0dd** [comment]
Confirming that it works now. It should be preferred_username since that's
the username from pocket-id

  header_map:
    user: X-Forwarded-Preferred-Username


from Frigate docs, these are the only supported header mappings:

Remote-User
Remote-Groups
Remote-Email
Remote-Name
X-Forwarded-User
X-Forwarded-Groups
X-Forwarded-Email
X-Forwarded-Preferred-Username
X-authentik-username
X-authentik-groups
X-authentik-email
X-authentik-name
X-authentik-uid
My config now works and frigate is able to identify the correct user. For
anyone else trying to make it work, I posted the frigate + traefik +
pocket-id configs above.

Thanks for pointing me to the right direction

**Reply by stonith404** [reply]
Great :)

**Comment by jsapede** [comment]
hello i'm totally stuck with trying to make frigate working with traefik + oauth2proxy,
could you add your fully working config including traefik compose and config.yml for frigate ? 
how did you implemented groups in pocketid to make it work ?
do you need to set a specific domain for oauth2-frigate.domain.com and where to make it point ?

**Comment by arunoruto** [comment]
I am using traefik with the [`traefik-oidc-auth`](https://github.com/sevensolutions/traefik-oidc-auth) plugin and the following configuration:
```yml
http:
  middlewares:
    pocket-id:
      plugin:
        traefik-oidc-auth:
          Secret: "..."
          Provider:
            Url: "..."
            ClientId: "..."
            ClientSecret: "..."
          Scopes: ["openid", "profile", "email", "groups"]
          Headers:
            - Name: "X-Forwarded-User"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "X-Forwarded-Groups"
              Value: "{{`{{with .claims.groups}}{{ range $i, $g := . }}{{if $i}},{{end}}{{$g}}{{end}}{{end}}`}}"
```
On frigates end, I only had to setup the following part:
```yml
proxy:
  header_map:
    user: x-forwarded-user
    role: x-forwarded-groups
```

I think pocket-id even has a built-in admin group from the start, but if not, you can always [remap](https://docs.frigate.video/configuration/authentication/#role-mapping) it!
