### DISCUSSION TITLE
Internal Server Error when PCKE option is turned on in Pocket ID OIDC clients setting

### DISCUSSION THREAD

**Discussion by DriftingShadows** [pocket-id/pocket-id#248] [Q&A]
Part of the problem may be that I do not completely understand oauth2 but when i enable PCKE, Pocket ID throws a 500 error 
![image](https://github.com/user-attachments/assets/c97fb5e2-2c95-431c-935d-c34322d2ba22)

And this is the error i see in the pocket id logs
```
pocket-id-pocket-id-1  | [GIN] 2025/02/18 - 14:32:33 | 400 |   49.918842ms |      172.16.7.1 | POST     "/api/oidc/token"
pocket-id-pocket-id-1  | Error #01: Invalid code verifier
```

I have a truenas scale machine with pocket id, oauth2-proxy  and npm running in dockge and just testing with a service like frigate. The flow works fine with PCKE turned off (can successfully sign in using passkey from my password manager).

pocket id
```
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    env_file: .env
    ports:
      - 3001:80
    volumes:
      - <directory>/pocket-id/data:/app/backend/data
    # Optional healthcheck  
    healthcheck:
      test: curl -f http://localhost/health
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
```

oauth2-proxy
```
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: unless-stopped
    user: root
    ports:
      - 4180:4180
    command: --config /oauth2-proxy1.cfg
    volumes:
      - <directory>/oauth2-proxy.cfg:/oauth2-proxy1.cfg
    networks:
      - ix-frigate_default
networks:
  ix-frigate_default:
    external: true
```

On NPM i just have frigate.domain.name forwarded to IP:4180 with no additional "Advanced" configurations.

Any help is greatly appreciated. Let me know if I need to provide more information.
