### DISCUSSION TITLE
Different BASE URL

### DISCUSSION THREAD

**Discussion by TwoSoulz** [pocket-id/pocket-id#302] [Q&A] [answered]
Hello, 
so Im an absolute newbie in reverse proxy things and I think pocket-id isnt the perfect one for that what I want. But maybe its very easy and you guys can help me. I want to change the BASE URL. What I mean with that:

Instead of https://test.example.de/ I want that everything runs under https://test.example.de/pid
Because I already run things under /.

My compose with Traefik at the moment looks like this:

```
  pocket-id:
    image: stonith404/pocket-id:latest
    container_name: pocket-id
    restart: unless-stopped
    environment:
      - PUBLIC_APP_URL=https://test.example.de/pocket-id
      - CADDY_DISABLED=true
    volumes:
      - "./pocket-id/data:/app/backend/data"
    labels:
      - "traefik.enable=true"

      # Frontend (Port 3000) unter /pocket-id
      - "traefik.http.routers.pocket-id.rule=Host(`test.example.de`) && PathPrefix(`/pocket-id`)"
      - "traefik.http.routers.pocket-id.entrypoints=websecure"
      - "traefik.http.routers.pocket-id.tls=true"
      - "traefik.http.routers.pocket-id.service=pocket-id"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=3000"

      # API + .well-known (Port 8080) unter /pocket-id/api und /pocket-id/.well-known
      - "traefik.http.routers.pocket-id-api.rule=Host(`test.example.de`) && PathPrefix(`/pocket-id/api/`, `/pocket-id/.well-known/`)"
      - "traefik.http.routers.pocket-id-api.entrypoints=websecure"
      - "traefik.http.routers.pocket-id-api.tls=true"
      - "traefik.http.routers.pocket-id-api.service=pocket-id-api"
      - "traefik.http.services.pocket-id-api.loadbalancer.server.port=8080"
```
