### DISCUSSION TITLE
CrowdSec Protection for Pocket-ID

### DISCUSSION THREAD

**Discussion by DJKatastrof** [pocket-id/pocket-id#621] [General]
Hey yall,

Just got CrowdSec working with Pocket-ID to automatically ban IPs that abuse the API!
Setup

Environment: Pocket-ID running in LXC container on Proxmox
Protection: Bans IPs after 3 failed requests (HTTP 400, 403, 429 errors)
Duration: 4 hour ban, 4 hour detection window

How it works

Reads Pocket-ID logs from systemd journal
Extracts HTTP status codes and IP addresses from GIN framework logs
Counts 400, 403 and 429 errors per IP
Bans IP for 4 hours after 3 bad requests within 4 hours
Automatically blocks traffic via iptables

Install Crowdsec and crowdsec-firewall-bouncer-iptables.
Create following parser, scenario and edit acquis.yaml

**/etc/crowdsec/acquis.yaml**
```
# PocketID service acquisition  
---
source: journalctl
journalctl_filter:
  - "_SYSTEMD_UNIT=pocketid.service"
labels:
  type: syslog

# Traditional file-based logs
---
source: file
filenames:
  - /var/log/syslog
  - /var/log/messages
labels:
  type: syslog
```

**/etc/crowdsec/parsers/s01-parse/pocketid-logs.yaml**
```
onsuccess: next_stage
debug: false
filter: "evt.Parsed.program == 'pocket-id'"
name: crowdsecurity/pocketid-logs
description: "Parse Pocket-ID logs from journald"
nodes:
  - grok:
      apply_on: message
      pattern: '\[GIN\] %{YEAR:year}/%{MONTHNUM:month}/%{MONTHDAY:day} - %{TIME:time} \| %{INT:http_status} \| %{DATA:duration} \|>
      statics:
        - meta: service
          value: http
        - meta: source_ip
          expression: evt.Parsed.client_ip
        - meta: http_status
          expression: evt.Parsed.http_status
        - meta: log_type
          value: pocketid_access
```

**/etc/crowdsec/scenarios/pocketid-error-limit.yaml**
```
type: leaky
name: crowdsecurity/pocketid-error-limit
description: "Ban IPs that generate multiple 400/403/429 errors in Pocket-ID"
filter: "evt.Meta.service == 'http' && evt.Meta.http_status in ['400','403','429']"
groupby: "evt.Meta.source_ip"
capacity: 2
leakspeed: "20s" 
blackhole: "45m"
labels:
  service: http
  type: bruteforce
  remediation: true
```
