### DISCUSSION TITLE
Pocket ID, OAuth2-Proxy, and Traefik v3

### DISCUSSION THREAD

**Discussion by ReclaimedBytes** [pocket-id/pocket-id#96] [Q&A]
Anyone got these working together, and wouldn't mind sharing their configs? When I go to the service I'm proxying, the OAuth2 screen comes up, but clicking the button to go Pocket ID doesn't do anything. Thanks!

**Comment by kmendell** [comment]
@ReclaimedBytes  I don't use Traefik or Oauth2-proxy with pocket id (yet at least) but if you want share you configs, I can try to help you out as best I can.

**Comment by exactlyaron** [comment]
I'm also trying to get something working with these three but no luck so far.

I've found a couple of issues on oauth2 repo which I'm fat fingered trying to work out but not there yet.

https://github.com/oauth2-proxy/oauth2-proxy/issues/1297
https://github.com/oauth2-proxy/oauth2-proxy/issues/46

**Comment by 123mariachi123** [comment]
I try to get it working just with Traefik. Previously i was using Authelia, then Authentik. But I'd like to swith to pocket id.
With both, Authelia and Authentik i was able to set up a middleware that was generic so that i could simply add it to a service (router in Traefik) by adding it as middleware.

E.g.
```yaml
http:
  routers:
    whoami:
      rule: "Host(`whoami.mydomain.com`)" 
      service: whoami-service
      priority: 10
      middlewares:
        - authentik
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
        options: external

  services:
    whoami-service:
      loadBalancer:
        servers:
          - url: "http://192.168.10.34:8181"
``` 

While the middleware looks like this (can be found in many howto's)
```yaml
http:
  middlewares:
    authentik:
      forwardAuth:
        address: http://192.168.10.22:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-entitlements
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```

I would like to achieve something similar with pocket id for services that do not support OIDC. Kind of a security-wrapper around my application. 
It's quite hard to find something on the web right now but i found this
[https://traefik-oidc-auth.sevensolutions.cc/docs/getting-started](https://traefik-oidc-auth.sevensolutions.cc/docs/getting-started)

Following the description i included the experimental plugin in my traefik.yaml and this middleware
```yaml
http:
  middlewares:
    oidcAuth:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: "https://pocketid.mydomain.com"
            ClientId: "<my-client-id>"
            ClientSecret: "<my-client-secret>"
            UsePkce: false
          Scopes: ["openid", "profile", "email"]
          CallbackUri: "https://pocketid.mydomain.com/oidc/callback"
          SessionCookie:
            Domain: ".mydomain.com"
```

And then add the "oidcAuth" as middlware to my whoami router shown above (instead of authentik middleware)

In pocket id i set up the following OIDC client (which may be wrong though)
<img width="1250" alt="screenshot" src="https://github.com/user-attachments/assets/41eeac59-460c-4422-8798-94c95646c64e" />

When i browse to https://whoami.mydomain.com i am forwarded to pocket id and successfully authorized. However, i do not get forwarded to whoami, instead i see a pocketid page that says "Something went wrong. Not Found"

Maybe its not even (yet?) possible what i try to acchieve with pocket id?

Help is very much appreciated :). Btw great project!


Edit:
The provider of the plugin mentioned above also include a working example here. This is what i tried to rebuild without success. Probably i am missing something?
[https://traefik-oidc-auth.sevensolutions.cc/docs/getting-started/callback-uri](https://traefik-oidc-auth.sevensolutions.cc/docs/getting-started/callback-uri) (at the bottom)

**Reply by cdanis** [reply]
Pocket-ID needs to callback to a URI which is served by the middleware plugin.  You need to explicitly set this up in your config.

Do something like this instead.

```yml
http:
  middlewares:
    oidcAuth:
      plugin:
        traefik-oidc-auth:
          CallbackUri: "https://traefikoidc.mydomain.com/oidc/callback"

  routers:
    traefikoidc:
      rule: "Host(`traefikoidc.mydomain.com`)"
      service: noop@internal
      middlewares:
        - oidcAuth
```

The plugin needs to receive the access token generated by Pocket-ID, so Pocket ID must be able to redirect the user's HTTP calls towards a path handled by the plugin.  Here we use a subdomain.  The `noop@internal` service is built into Traefik, and returns 418 I'm A Teapot for all requests -- but the plugin intercepts and handles all the HTTP routes we care about.

**Reply by 123mariachi123** [reply]
**EDIT:** If someone ever reads this, i was doing it wrong here. Ignore it and see the comment further down

Thanks a lot @cdanis!

I don't know if i really understand why it works this way but it works great!
My workflow now, just to confirm that i do it correctly:

I set up a middleware in my middlware.yaml (here the relevant part):
```yaml
http:
  middlewares:
    oidcAuth:
      plugin:
        traefik-oidc-auth:
          # CallbackUri: "https://traefikoidc.mydomain.com/oidc/callback"
          Provider:
            Url: "https://pocketid.mydomain.com"
            ClientId: "<my-clientid>"
            ClientSecret: "<my-clientsecret>"
            UsePkce: false
          Scopes: ["openid", "profile", "email"]
```

Since i have all my routers in separate files, i add a new traefikoidc.yaml:
```yaml
http:
  routers:
    traefikoidc:
      rule: "Host(`traefikoidc.mydomain.com`)"
      service: noop@internal
      middlewares:
        - oidcAuth
```

And then, i add the middleware with the callback URI to each application that i want to wrap into pocket id:
```yaml
http:
  middlewares:
    oidcAuth:
      plugin:
        traefik-oidc-auth:
          CallbackUri: "https://traefikoidc.mydomain.com/oidc/callback"

  routers:
    whoami:
      rule: "Host(`whoami.mydomain.com`)" 
      service: whoami-service
      priority: 10
      middlewares:
        - oidcAuth
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
        options: external

  services:
    whoami-service:
      loadBalancer:
        servers:
          - url: "http://192.168.10.34:8181"

```

The same middleware block goes to all applications that i want to wrap and finally in pocket id i create a callback URI for each application like this

<img width="1266" alt="Bildschirmfoto 2025-01-20 um 21 01 32" src="https://github.com/user-attachments/assets/9014c04a-82c2-4982-b938-4dce13e3b0d9" />

What i don't understand is why i need to add the middleware block to each application yaml separately. I tried adding it directly to the middlware.yaml but then it doesnt work. Why?

Anyways, thanks a lot for your fast response!

**Reply by Fayyaadh** [reply]
Hi

I was playing around with this yesterday and finally got it to work.

In traefik's `config.yaml` file, I added this to the bottom:

```yaml
experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.5.0"
```

And then setup the middleware in the `middlewares.yaml` files:

```yaml
http:
  middleware:
    pocket-id:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: "https://pocket-id.domain.me"
            ClientId: "Id from Pocket ID goes here"
            ClientSecret: "Secret from Pocket ID goes here"
            # UsePkce: true # Or use PKCE if your Provider supports this
          Scopes: ["openid", "profile", "email"]
```

And then for each service that you want to use Pocket ID with, your router setup will look like this:

```yaml
http:
  routers:
    service-https:
      entryPoints:
        - websecure
      rule: Host(`service.domain.me`)
      service: service_name
      middlewares: pocket-id
```

So basically, just enable the oidc plugin once off, set it up once off and add 1 line of code per router.

**Reply by 123mariachi123** [reply]
Thanks @Fayyaadh. Forgot to post but in the end i did it exactly as you described and everything is working fine. Don't know what went wrong in my first attempt though.

**Reply by cdanis** [reply]
> What i don't understand is why i need to add the middleware block to each application yaml separately. I tried adding it directly to the middlware.yaml but then it doesnt work. Why?

If you're sure want to attach it to each and every router, you can make it one of the default middlewares for the entire entrypoint: https://doc.traefik.io/traefik/routing/entrypoints/#middlewares

**Reply by JohnDoe-dev-spec** [reply]
> Hi
> 
> I was playing around with this yesterday and finally got it to work.
> 
> In traefik's `config.yaml` file, I added this to the bottom:
> 
> ```yaml
> experimental:
>   plugins:
>     traefik-oidc-auth:
>       moduleName: "github.com/sevensolutions/traefik-oidc-auth"
>       version: "v0.5.0"
> ```
> 
> And then setup the middleware in the `middlewares.yaml` files:
> 
> ```yaml
> http:
>   middleware:
>     pocket-id:
>       plugin:
>         traefik-oidc-auth:
>           Provider:
>             Url: "https://pocket-id.domain.me"
>             ClientId: "Id from Pocket ID goes here"
>             ClientSecret: "Secret from Pocket ID goes here"
>             # UsePkce: true # Or use PKCE if your Provider supports this
>           Scopes: ["openid", "profile", "email"]
> ```
> 
> And then for each service that you want to use Pocket ID with, your router setup will look like this:
> 
> ```yaml
> http:
>   routers:
>     service-https:
>       entryPoints:
>         - websecure
>       rule: Host(`service.domain.me`)
>       service: service_name
>       middlewares: pocket-id
> ```
> 
> So basically, just enable the oidc plugin once off, set it up once off and add 1 line of code per router.

I managed to get Pocket-ID working with your post, thank you!

I do have one question if anyone knows. There are some sites where for example the API needs to be excluded from pocket-id so that apps on my phone can work without going through the pocket-id authentication. 

Is there an obvious way to do this within traefik or pocket-id itself?

Thank you, hopefully this made sense!

=========================

EDIT

=========================

Nevermind, i should've just googled :) managed to figure it out, adding an additional label to my docker containers such as;

> traefik.http.routers.tautulli2.rule: (Host(`tautulli.com`) && PathPrefix(`/api`))

This worked for me! thank you

**Reply by Fayyaadh** [reply]
Hey

It's a pleasure.

I think this post might help: https://stackoverflow.com/questions/70266406/traefik-apply-middleware-to-router-except-a-specific-path

Have another router that matches on the API path and give that a higher priority, and don't apply the middleware to that router.

**Reply by kayjay-madman** [reply]
> Hi
> 
> I was playing around with this yesterday and finally got it to work.
> 
> In traefik's `config.yaml` file, I added this to the bottom:
> 
> ```yaml
> experimental:
>   plugins:
>     traefik-oidc-auth:
>       moduleName: "github.com/sevensolutions/traefik-oidc-auth"
>       version: "v0.5.0"
> ```
> 
> And then setup the middleware in the `middlewares.yaml` files:
> 
> ```yaml
> http:
>   middleware:
>     pocket-id:
>       plugin:
>         traefik-oidc-auth:
>           Provider:
>             Url: "https://pocket-id.domain.me"
>             ClientId: "Id from Pocket ID goes here"
>             ClientSecret: "Secret from Pocket ID goes here"
>             # UsePkce: true # Or use PKCE if your Provider supports this
>           Scopes: ["openid", "profile", "email"]
> ```
> 
> And then for each service that you want to use Pocket ID with, your router setup will look like this:
> 
> ```yaml
> http:
>   routers:
>     service-https:
>       entryPoints:
>         - websecure
>       rule: Host(`service.domain.me`)
>       service: service_name
>       middlewares: pocket-id
> ```
> 
> So basically, just enable the oidc plugin once off, set it up once off and add 1 line of code per router.

What callback URL are you using in Pocket Id UI to get the OIDC client set up for the generic middleware? I am stuck at this step.

**Reply by 123mariachi123** [reply]
Be careful, you are using v0.5.0 while the current release is [v0.11.0](https://github.com/sevensolutions/traefik-oidc-auth/releases/tag/v0.11.0); see also [the documentation](https://traefik-oidc-auth.sevensolutions.cc/docs/getting-started/middleware-configuration)

My `config.yaml`:
```yaml
experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.11.0"
```

my `middleware.yaml` (note the `http: middlewares` -> plural) 
```yaml
http:
  middlewares:
    oidcAuth:
      plugin:
        traefik-oidc-auth:
          Secret: "<32 char secret as described in the docs>"
          Provider:
            Url: "https://pocketid.example.com"
            ClientId: "<client id of client traefik>"
            ClientSecret: "<client secret of client traefik>"
            TokenValidation: "IdToken"
            UsePkce: true
          Scopes: ["openid", "profile", "email"]
```
my routers look basically the same as above except i chain the middlewares.

And for generic middleware my pocket-id client looks like this (note that this is the client id and secret i use in the `middleware.yaml` above:

<img width="1608" alt="Bildschirmfoto 2025-05-07 um 19 40 39" src="https://github.com/user-attachments/assets/2396eade-3a85-40c0-a685-4d2edff7fc45" />

So for this generic middleware, you can add all routers to the same client in pocket-id.

Hope that helps
