### ISSUE TITLE
🚀 Feature: Docker containers of each component (backend & frontend)

### ISSUE THREAD

**Issue by wargio** [pocket-id/pocket-id#148]
### Feature description

It would be nice to have `pocket-id:latest-frontend` & `pocket-id:latest-backend` for more advance users.

### Pitch

Currently i'm running the frontend and the backend without caddy by overwriting the entrypoint.sh script (this is to avoid having 2 reverse proxy in chain). this is a bit hacky and having just two images for each component would be great.

**Comment by kmendell** [comment]
Hi @wargio  You can build the backend / frontend manually and use those or push your own docker image, I think the idea is to keep it simple for users, so for more advanced users I think that may be the approach we should take, @stonith404 do you agree? 

If you follow the Standalone installation docs, that will get you the build steps required for what I'm describing above.

Though i do see what you are asking for and could see how it's useful as well.

**Comment by stonith404** [comment]
In my personal projects, I use separate images for the frontend and backend. However, for projects like this, I prefer a single image because it simplifies the installation process and reduces potential setup issues.

@wargio, couldn’t you just expose the backend and frontend ports directly from the container? Caddy would still run, but you’d be bypassing it.

I also agree with @kmendell’s opinion. For advanced users, building the image themselves likely wouldn’t be a problem.

**Comment by wargio** [comment]
This is exactly what i do and i just disable caddy from running, since i don't need it.

```yaml
services:
  pocket-id:
    image: registry.domain.local/stonith404/pocket-id:latest
    container_name: pocket-id
    environment:
      - PUID=1000
      - PGID=1000
      - PUBLIC_APP_URL=https://sso.domain.local
      - MAXMIND_LICENSE_KEY=
      - DB_PROVIDER=sqlite
      - HOST=0.0.0.0
    ports:
      - 127.0.0.1:12673:80
    volumes:
      - ./data:/app/backend/data
      - ./entrypoint.sh:/app/scripts/docker/entrypoint.sh:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
```

and the `entrypoint.sh`

```
echo "Starting frontend..."
node frontend/build &

echo "Starting backend..."
cd backend && ./pocket-id-backend &

wait
```
