### ISSUE TITLE
🐛 Bug Report: Creating admin Passkey returns `Error: 'rp.id' cannot be used with the current origin` in Web Console

### ISSUE THREAD

**Issue by Sumtin** [pocket-id/pocket-id#260]
### Reproduction steps

App appears to run find, no errors in logs.  I am able to change my admin name/email/etc.  But I get an error when generating my admin Passkey.

### Expected behavior

Create a passkey and forward to my browser.

### Actual Behavior

1. System responds with `An unknown error occurred`
2. Checking the web console, I see the following output:

![Image](https://github.com/user-attachments/assets/b6a9a5a7-afd6-4e76-9923-ff60510d99a7)

### Version and Environment

v0.35.1

Running Nginx Proxy Manager in front, disabled Caddy.  Compose and .env below:

```
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - /home/admin/pocket-id/volume:/app/backend/data
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
```

```
CADDY_DISABLED=true
PUBLIC_APP_URL=https://sub.domain.com
TRUST_PROXY=true
MAXMIND_LICENSE_KEY=redacted
PUID=1000
PGID=1000
```

NPM Configs:
![Image](https://github.com/user-attachments/assets/4cccf5fd-6ab6-44ba-abb9-11fec39a5306)
![Image](https://github.com/user-attachments/assets/a1bf47fb-4b9a-4f66-995d-44c538b8ba7d)
![Image](https://github.com/user-attachments/assets/a8317a0b-e582-4c94-bf31-cdd828de39a3)
![Image](https://github.com/user-attachments/assets/0e8b5e23-a5ca-404a-b6c8-803ca6020bfa)

### Log Output

Logs don't show any errors.
