### ISSUE TITLE
🐛 Bug Report: Unable to install pocket-id using docker and treafik: ECONNREFUSED

### ISSUE THREAD

**Issue by ArthurHuyghe** [pocket-id/pocket-id#343]
### Reproduction steps

I followed the installation instructions from the documentation, copied compose.yml and .env and changed the necessary variables. I wasn't able to install pocket-id successfully and searched through the discussions,  issues and on the web for solutions, but did not found any.

### Expected behavior

The docker container should be detected by treafik and pocket-id should be able to be setup .

### Actual Behavior

The container starts up, the logs show no errors, but it isn't picked up by treafik. I manually added pocket-id to treafiks static config-file, and now when I surf to pocket-id, I get an error stating something critical went wrong and `Failed to get application configuration: connect ECONNREFUSED 127.0.0.1:8080` appears in the logs. After a while the healtcheck fails aswell.

### Version and Environment

Version information:
```
Pocket-Id: v0.40.0
Traefik: v3.3.2
Docker: v24.0.2
```
Compose-file: 
``` yaml
---
networks:
 proxy_network:
  external: true

services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v0.40.0
    container_name: pocket-id
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - 3000:80 # not needed since we are using traefik 
    volumes:
      - "./data:/app/backend/data"
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    
    networks:
      proxy_network:
    # traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.pocket-id-backend-router.entrypoints=websecure
      - traefik.http.routers.pocket-id-backend-router.rule=Host(`pocket-id.SECRET`) && (PathPrefix(`/api/`) || PathPrefix(`/.well-known/`))
      - traefik.http.routers.pocket-id-backend-router.tls=true
      - traefik.http.routers.pocket-id-backend-router.service=pocket-id-backend-service
      - traefik.http.services.pocket-id-backend-service.loadbalancer.server.port=8080
      - traefik.http.routers.pocket-id-frontend-router.entrypoints=websecure
      - traefik.http.routers.pocket-id-frontend-router.rule=Host(`pocket-id.SECRET`)
      - traefik.http.routers.pocket-id-frontend-router.tls=true
      - traefik.http.routers.pocket-id-frontend-router.service=pocket-id-frontend-service
      - traefik.http.services.pocket-id-frontend-service.loadbalancer.server.port=3000
```
.env-file:
```yaml
# See the README for more information: https://github.com/pocket-id/pocket-id?tab=readme-ov-file#environment-variables
PUBLIC_APP_URL=https://pocket-id.SECRET
MAXMIND_LICENSE_KEY=
PUID=1033
PGID=65537
TZ="Europe/Brussels"

# traefik
CADDY_DISABLED=true
TRUST_PROXY=true
HOST='pocket-id'

```
traefiks config.yml:
```yaml
tls:
  options:
    modern:
      minVersion: VersionTLS13

http:
  routers:
    
    #test:
    pocket-id-backend-router:
      entryPoints:
        - websecure
      rule: "Host(`pocket-id.SECRET`) && (PathPrefix(`/api/`) || PathPrefix(`/.well-known/`))"
      service: pocket-id-backend-service
      tls: true

    pocket-id-frontend-router:
      entryPoints:
        - websecure
      rule: "Host(`pocket-id.SECRET`)"
      service: pocket-id-frontend-service
      tls: true

services:
    #test:
    pocket-id-backend-service:
      loadBalancer:
        servers:
          - url: http://pocket-id:8080
    pocket-id-frontend-service:
      loadBalancer:
        servers:
          - url: http://pocket-id:3000
```

### Log Output

![Image](https://github.com/user-attachments/assets/ad30040e-a685-4d5f-9bbd-7549e0006921)

I couldn't find any other log-files.
