### ISSUE TITLE
🐛 Bug Report: Error #01: Failed to lookup Client-side Discoverable Credential: record not found

### ISSUE THREAD

**Issue by truthsword** [pocket-id/pocket-id#434]
### Reproduction steps

New installation. Container on Debian 12. Using Nginx Proxy Manager.

On setup, I created a passkey saved to Bitwarden (Vaultwarden), This appeared in settings.

Next I added a hardware key (Yubikey). When entered, this did not appear alongside the first passkey. I refreshed browser tab and got error.

So I opened up PID using the subdomain. It asked to autheticate. Both the passkey and the yubikey failed authetication.

It's dead, Jim. Please advise.

### Expected behavior

Passkey works

### Actual Behavior

Authentication fails

### Version and Environment

Just downloaded today... so the "latest"  Otherwise, I can't get into the app to get a version number.

### Log Output

```
pocket-id-1  | Error #01: Failed to lookup Client-side Discoverable Credential: record not found
pocket-id-1  | [GIN] 2025/04/11 - 21:47:47 | 500 |      608.88µs |    192.168.96.1 | POST     "/api/webauthn/login/finish"                                                                                                
pocket-id-1  | Error #01: Failed to lookup Client-side Discoverable Credential: record not found
pocket-id-1  | [GIN] 2025/04/11 - 21:49:05 | 200 |     148.799µs |             ::1 | GET      "/api/application-configuration"
pocket-id-1  | [GIN] 2025/04/11 - 21:49:05 | 200 |      164.34µs |             ::1 | GET      "/api/application-configuration"       
```

**Comment by kmendell** [comment]
What does your Nguni config look like? also what does your environment look like for pocket id?

**Comment by truthsword** [comment]
PocketID compose:

```
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocket_id
    restart: unless-stopped
    env_file: .env
    ports:
      - 81211:80
    volumes:
      - data:/app/backend/data
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

volumes:
  data:
```

Nginx Proxy Manager:
![](https://i.imgur.com/gaCVZZG.png)

PocketID seems to be running fine by itself, until I try to set up Portainer (also connected via Nginx Proxy Manager).
