### ISSUE TITLE
🚀 Feature: Add ability to create log files

### ISSUE THREAD

**Issue by gtensolr** [pocket-id/pocket-id#515]
### Feature description

The proposed feature if for Pocket ID to generate log files, so they could be parsed by other tools. It would be important to have the option of `log level`, `file_location` and `format`. This could be set on environmental variables or even within the GUI

### Pitch

On several containers that are related to Authentication, they can be configured to generate log files, that can be parsed by tools such as Fail2ban and Crowdsec. Although the attack vector for Pocket ID is quite small, there's still a possibility for a malicious actor to attempt to brute force the `Login Code`. Even if there are no codes configured (thus no real attack vector), it's an important source of info for firewall and blocking malicious IPs.

**Comment by kmendell** [comment]
You Can export the logs from docker it self using the logging section:

```
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog.example.com:12201"
        tag: "first-logs"
```

This would send all of that to your log server of choice.
