### ISSUE TITLE
🐛 Bug Report: Login not possible after 1.0.0 migration

### ISSUE THREAD

**Issue by thueske** [pocket-id/pocket-id#568]
### Reproduction steps

.env:

```
APP_URL=https://auth.mydomain.com
TRUST_PROXY=true
MAXMIND_LICENSE_KEY=mykey
```

docker-compose.yml:

```
services:
  app:
    image: ghcr.io/pocket-id/pocket-id
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    networks:
      proxy_apps:

volumes:
  app_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
```

### Expected behavior

Login as normal

### Actual Behavior

<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/57eae0c9-8721-479a-b500-bac38c7c4337" />

### Version and Environment

1.0.0 (with https://pocket-id.org/docs/setup/migrate-to-v1 done)

### Log Output

No relevant container logs.
