### ISSUE TITLE
🐛 Bug Report: Login not possible on v1.0.0

### ISSUE THREAD

**Issue by PsychotherapistSam** [pocket-id/pocket-id#569]
### Reproduction steps

I have Pocket ID running behind nginxproxymanager and that has worked beautifully so far. After updating to v1.0.0 I get the error described below.
I think I followed everything in the Migration Guide, but still can't get it to work anymore.

### Expected behavior

I should be able to log in :D

### Actual Behavior

When I log in I get the following error message in the server log:
pocket-id-1  | [GIN] 2025/05/25 - 07:02:33 | 500 |    1.947389ms |    192.168.1.52 | POST     "/api/webauthn/login/finish"
pocket-id-1  | Error #01: Failed to lookup Client-side Discoverable Credential: record not found

On the frontend:
"Something went wrong. Please try to sign in again."

And in the browser console:
{"error":"Something went wrong"} for the above 500 API call

### Version and Environment

<details><summary>docker-compose.yml</summary>
<p>

```yaml
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    env_file: .env
    ports:
      - 3210:1411
    volumes:
      - ./data:/app/backend/data
    healthcheck:
      test: curl -f http://localhost:1411/healthz
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
```

</p>
</details> 

<details><summary>.env</summary>
<p>

```ini
APP_URL=https://auth.domain.tld
TRUST_PROXY=true
PUID=1000
PGID=1000
```

</p>
</details>
