### ISSUE TITLE
🐛 Bug Report: Server Not Starting On First Install

### ISSUE THREAD

**Issue by matt-hogan** [pocket-id/pocket-id#668]
### Reproduction steps

When running Pocket ID for the first time with Postgres and `UI_CONFIG_DISABLED` as `true`, the server fails to startup.  This bug can be reproduced with the following docker compose.

```yaml
volumes:
  postgres:
  pocket-id:

services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1.4.0
    environment:
      APP_URL: http://localhost:1411
      TRUST_PROXY: false
      UI_CONFIG_DISABLED: true
      DB_PROVIDER: postgres
      DB_CONNECTION_STRING: postgres://pocketid:password@postgres:5432/pocketid
    ports:
      - 1411:1411
    volumes:
      - pocket-id:/app/data
  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: pocketid
      POSTGRES_USER: pocketid
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
```

Based on my debugging, the database query for getting the internal fields isn't returning.  https://github.com/pocket-id/pocket-id/blob/88832d4bc9647f545ce36bc1d3afdee581dd4ef5/backend/internal/service/app_config_service.go#L423-L427

### Expected behavior

The server should start up

### Actual Behavior

The server fails to start

### Version and Environment

v1.4.0

### Log Output

This is the only log output
```
Creating group 1000...
Creating user 1000...
```
